services:
   mariadb:
    image: mariadb:11.3
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=xyna
      - MYSQL_USER=xyna
      - MYSQL_ROOT_PASSWORD=db_root_pwd
      - MYSQL_PASSWORD=xyna_db_pwd
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'select 1;'"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s
    
   xyna:
    image: xynafactory/factory:0.9.1
    configs:
     - source: userarchive.XYNA.password
       target: /userarchive/XYNA.password
     - source: userarchive.XYNA.name
       target: /userarchive/XYNA.name
     - source: userarchive.XYNA.role
       target: /userarchive/XYNA.role
    expose:
      - 4245
    healthcheck:
      test: "echo -n $$'status\x1D\x1D\x04' | nc 127.0.0.1 4242 2>&1"
      interval: 1s
      timeout: 5s
      retries: 60
      start_period: 180s
    depends_on:
      mariadb:
        condition: service_healthy

   modeller:
    image: xynafactory/modeller:0.9
    entrypoint: ["apachectl", "-D", "FOREGROUND"] 
    environment:
      - MODELLER_PORT=8000
      - MODELLER_HOSTNAME="xyna"
      - GUIHTTP_URL="http://xyna:4245"
      - GUIHTTP_COOKIE_FLAGS="off"
      - RESOLVER="127.0.0.11"
    ports:
      - 8000:8000
    depends_on:
      - xyna
configs:
 userarchive.XYNA.name:
   content: XYNA
 userarchive.XYNA.password:
   content: XYNAPASSWORD
 userarchive.XYNA.role:
   content: ADMIN

