services:
   mariadb:
    image: ${MARIADB_IMAGE}
    container_name: ${MARIADB_CONTAINER_NAME}
    # see https://docs.docker.com/reference/compose-file/services/#pull_policy
    pull_policy: ${MARIADB_PULL_POLICY}
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    expose:
      - ${MARIADB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u $$MARIADB_USER -p$$MARIADB_PASSWORD $$MARIADB_DATABASE -e 'select 1;'"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s

   xyna:
     # platform: linux/amd64 #Has to be set for Mac users
    image: ${XYNA_IMAGE}
    container_name: ${XYNA_CONTAINER_NAME}
    # see https://docs.docker.com/reference/compose-file/services/#pull_policy
    pull_policy: ${XYNA_PULL_POLICY}
    # SYNC_CONTAINER_LIFECYCLE_TO_FACTORY: set to false to keep the container running independently of the xynafactory process
    environment:
      - SYNC_CONTAINER_LIFECYCLE_TO_FACTORY=true
      - USERARCHIVE_XMLFILEPATH=defaultHISTORY/userarchive.xml
      - USERARCHIVE_MOUNTDIRECTORY=/userarchive
      - POOLDEFINITION_XMLFILEPATH=defaultHISTORY/pooldefinition.xml
      - POOLDEFINITION_MOUNTDIRECTORY=/pooldefinition
    volumes:
      - xyna-userarchive:/userarchive:rw
      - xyna-pooldefinition:/pooldefinition
      - xyna-tmp:/tmp
      - xyna-revisions:/opt/xyna/xyna_001/revisions
      - xyna-xmomreposisotiy:/opt/xyna/xyna_001/xmomrepository
      - xyna-xnwhclasses:/opt/xyna/xyna_001/server/xnwhclasses
      - xyna-gen:/opt/xyna/xyna_001/server/gen
      - xyna-storage:/opt/xyna/xyna_001/server/storage
    configs:
     - source: userarchive.XYNA.password
       target: /userarchive/${XYNAUSER_USERNAME}.password
     - source: userarchive.XYNA.name
       target: /userarchive/${XYNAUSER_USERNAME}.name
     - source: userarchive.XYNA.role
       target: /userarchive/${XYNAUSER_USERNAME}.role
     - source: pooldefinition.password
       target: /pooldefinition/Xyna-Infra-Pool.password
     - source: pooldefinition.password
       target: /pooldefinition/Xyna-Infra-Pool_dedicated.password
     - source: pooldefinition.user
       target: /pooldefinition/Xyna-Infra-Pool.user
     - source: pooldefinition.user
       target: /pooldefinition/Xyna-Infra-Pool_dedicated.user
     - source: pooldefinition.connectstring
       target: /pooldefinition/Xyna-Infra-Pool.connectstring
     - source: pooldefinition.connectstring
       target: /pooldefinition/Xyna-Infra-Pool_dedicated.connectstring
     - source: pooldefinition.type
       target: /pooldefinition/Xyna-Infra-Pool.type
     - source: pooldefinition.type
       target: /pooldefinition/Xyna-Infra-Pool_dedicated.type
    expose:
      - 4245
    healthcheck:
      test: "echo -n $$'status\x1D\x1D\x04' | nc 127.0.0.1 4242 2>&1"
      interval: 1s
      timeout: 5s
      retries: 60
      start_period: 180s
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
    # see https://docs.docker.com/engine/network/#published-ports
      - "8000-8010"

   modeller:
    image: ${MODELLER_IMAGE}
    container_name: ${MODELLER_CONTAINER_NAME}
    # see https://docs.docker.com/reference/compose-file/services/#pull_policy
    pull_policy: ${MODELLER_PULL_POLICY}
    entrypoint: ["apachectl", "-D", "FOREGROUND"]
    environment:
      - MODELLER_PORT=${MODELLER_PORT}
      # The value of XYNA_HOSTNAME must match the value of the xyna service
      - XYNA_HOSTNAME=xyna
      - APACHE_LOG_DIR=/var/log/apache2
    ports:
    # see https://docs.docker.com/engine/network/#published-ports
      - ${MODELLER_PORT}:${MODELLER_PORT}
    depends_on:
      - xyna

# The values of the pooldefinition variables must match the values in the mariadb service
configs:
  userarchive.XYNA.name:
    content: |
      ${XYNAUSER_USERNAME}
  userarchive.XYNA.password:
    content: |
      ${XYNAUSER_PASSWORD}
  userarchive.XYNA.role:
    content: |
      ${XYNAUSER_ROLE}
  pooldefinition.password:
    content: |
      ${MARIADB_PASSWORD}
  pooldefinition.user:
    content: |
      ${MARIADB_USER}
  pooldefinition.connectstring:
    content: |
      jdbc:mariadb://mariadb:${MARIADB_PORT}/${MARIADB_DATABASE}
  pooldefinition.type:
    content: |
      MySQL

volumes:
  xyna-userarchive:
  xyna-pooldefinition:
  xyna-tmp:
  xyna-revisions:
  xyna-xmomreposisotiy:
  xyna-xnwhclasses:
  xyna-gen:
  xyna-storage:
