services:
   mariadb:
    image: mariadb:11.3
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=xyna
      - MYSQL_USER=xyna
      - MYSQL_ROOT_PASSWORD=db_root_pwd
      - MYSQL_PASSWORD=xyna_db_pwd
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'select 1;'"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s
    
   xyna:
     # platform: linux/amd64 #Has to be set for Mac users
    image: xynafactory/factory:1.0.2
    # SYNC_CONTAINER_LIFECYCLE_TO_FACTORY: set to false to keep the container running independently of the xynafactory process
    # The values of the MYSQL_... variables must match the values in the mariadb service
    environment:
      - SYNC_CONTAINER_LIFECYCLE_TO_FACTORY=true
      - MYSQL_USER=xyna
      - MYSQL_PASSWORD=xyna_db_pwd
      - CONNECT_STRING="jdbc:mariadb://mariadb:3306/xyna"
      - USERARCHIVE_XMLFILEPATH=defaultHISTORY/userarchive.xml
      - USERARCHIVE_MOUNTDIRECTORY=/userarchive
    volumes:
      - xyna-userarchive:/userarchive:rw
      - xyna-pooldefinition:/pooldefinition
      - xyna-tmp:/tmp
      - xyna-revisions:/opt/xyna/xyna_001/revisions
      - xyna-xmomreposisotiy:/opt/xyna/xyna_001/xmomrepository
      - xyna-xnwhclasses:/opt/xyna/xyna_001/server/xnwhclasses
      - xyna-gen:/opt/xyna/xyna_001/server/gen
      - xyna-storage:/opt/xyna/xyna_001/server/storage
    configs:
     - source: userarchive.XYNA.password
       target: /userarchive/XYNA.password
     - source: userarchive.XYNA.name
       target: /userarchive/XYNA.name
     - source: userarchive.XYNA.role
       target: /userarchive/XYNA.role
    expose:
      - 4245
    healthcheck:
      test: "echo -n $$'status\x1D\x1D\x04' | nc 127.0.0.1 4242 2>&1"
      interval: 1s
      timeout: 5s
      retries: 60
      start_period: 180s
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8000-8010"

   modeller:
    image: xynafactory/modeller:0.10
    entrypoint: ["apachectl", "-D", "FOREGROUND"]
    environment:
      - MODELLER_PORT=8000
      - MODELLER_HOSTNAME="xyna"
      - GUIHTTP_URL="http://xyna:4245"
      - GUIHTTP_COOKIE_FLAGS="off"
      - RESOLVER="127.0.0.11"
    ports:
      - 8000:8000
    depends_on:
      - xyna

configs:
  userarchive.XYNA.name:
    content: |
      XYNA
  userarchive.XYNA.password:
    content: |
      XYNAPW
  userarchive.XYNA.role:
    content: |
      ADMIN

volumes:
  xyna-userarchive:
  xyna-pooldefinition:
  xyna-tmp:
  xyna-revisions:
  xyna-xmomreposisotiy:
  xyna-xnwhclasses:
  xyna-gen:
  xyna-storage:

