name: Build Containers

on:
  # to be called from xyna-factory repo
  workflow_call:
    inputs:
        artifact-url:
            required: true
            type: string

  workflow_dispatch:
    inputs:
      artifact-url:
        description: 'URL zu XynaFactory*.tar.zip'
        required: true
        type: string
        
jobs:
  build-containers:
    runs-on: ubuntu-latest

    strategy:
       matrix:
           base-image: ["oraclelinux:7", "oraclelinux:9", "ubuntu:22.04"]
           
    steps:
    - name: Download Xyna Factory artifact
      run: |
          wget ${{ inputs.artifact-url }} && \
          unzip XynaFactory*.zip  && \
          rm -f XynaFactory*.zip && \
          tar xvf XynaFactory*.tar && \
          rm -f XynaFactory*.tar && \
          zip XynaFactory_v.zip XynaFactory*

    - name: Check out repo
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Move Xyna and get Tags
      id: tags
      run: |
          mv XynaFactory_v.zip xynabase
          BASE_IMAGE_NAME=$(echo -n ${{ matrix.base-image }} | sed 's/[:.]/-/g' )
          echo "BASE_IMAGE_NAME=$BASE_IMAGE_NAME" >> "$GITHUB_OUTPUT"
          RUNS_AT=$(date -u +"%Y%m%dT%H%M%SZ")
          echo "RUNS_AT=$RUNS_AT" >> "$GITHUB_OUTPUT"
          source xynabase/build.shx
          echo "PREREQ_INSTALL_PARAMS=$PREREQ_INSTALL_PARAMS" >> "$GITHUB_OUTPUT"

    # https://github.com/marketplace/actions/build-and-push-docker-image
    - name: Build base image for ${{ matrix.base-image }}
      id: base-image-build
      uses: docker/build-push-action@v5
      with:
          context: xynabase
          push: false
          build-args: |
              PREREQ_INSTALL_PARAMS=${{ steps-tags.outputs.PREREQ_INSTALL_PARAMS }}
              OS_IMAGE=${{ matrix.base-image }}
              JAVA_VERSION=11
          tags: xynabase:${{ steps.tags.outputs.BASE_IMAGE_NAME }}-${{ steps.tags.outputs.RUNS_AT }}

    - name: Build prod image for ${{ matrix.base-image }}
      uses: docker/build-push-action@v5
      with:
          context: xynaprod
          push: false
          build-args: |
              XYNABASE_IMAGE=${{ steps.base-image-build.imageid }}
          tags: xynaprod:${{ steps.tags.outputs.BASE_IMAGE_NAME }}-${{ steps.tags.outputs.RUNS_AT }}

    - name: Build dev image for ${{ matrix.base-image }}
      uses: docker/build-push-action@v5
      with:
          context: xynadev
          push: false
          build-args: |
              XYNABASE_IMAGE=${{ steps.base-image-build.imageid }}
          tags: xynadev:${{ steps.tags.outputs.BASE_IMAGE_NAME }}-${{ steps.tags.outputs.RUNS_AT }}
